name: Build Android APK

on:
  push:
    branches:
      - main  # Baut die APK automatisch, wenn Änderungen auf 'main' gepusht werden

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository klonen
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Installiere Abhängigkeiten
        run: npm install
      
      - name: Baue die APK
        run: |
          cd android
          ./gradlew assembleRelease
      
      - name: APK speichern
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: android/app/build/outputs/apk/release/