name: Build Android APK

on:
  push:
    branches:
      - main  # Baut die APK automatisch, wenn Änderungen auf 'main' gepusht werden

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository klonen
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Installiere Abhängigkeiten
        run: npm install
      
      - name: Baue die App
        run: echo "Kein Android-Projekt          erkannt. Überspringe Build."
      
      - name: Speichere APK als Artifact
  uses: actions/upload-artifact@v4
  with:
    name: app-release
    path: android/app/build/outputs/**/*.apk